name: apns-once

on:
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          pip install "PyJWT>=2.8" "cryptography>=42"

      - name: Write inline APNs key (PEM)
        shell: bash
        run: |
          set -euo pipefail
          umask 077
          {
          echo '-----BEGIN PRIVATE KEY-----'
          echo 'MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfUyrzATs1Sjn4u9w'
          echo 'YeJH3LGx67sZPBoVJxHW3C7+dDWgCgYIKoZIzj0DAQehRANCAAQ+sq5rw5HiL6Jo'
          echo 'LsGWWVfDqTmnYR9LqkKWG3ea+7flLPbRo6UKyuRyQXZ/wrRmVMR+Q5IkrPt4ogIt'
          echo 'Mig6kHa4'
          echo '-----END PRIVATE KEY-----'
          } > apns_key.p8
          # CRLF対策 & 読めるか検証
          sed -i 's/\r$//' apns_key.p8
          openssl pkey -in apns_key.p8 -noout >/dev/null
          echo "✅ APNs key OK"

      - name: Build JWT
        id: jwt
        run: |
          set -euo pipefail
          python - <<'PY' > token.txt
          import time, jwt
          from cryptography.hazmat.primitives import serialization
          TEAM_ID = "8KVP2QK7BX"
          KEY_ID  = "5W5TK89GQC"
          with open("apns_key.p8","rb") as f:
              key = serialization.load_pem_private_key(f.read(), password=None)
          token = jwt.encode(
              {"iss": TEAM_ID, "iat": int(time.time())},
              key, algorithm="ES256",
              headers={"kid": KEY_ID}
          )
          print(token)
          PY
          echo "token=$(cat token.txt)" >> "$GITHUB_OUTPUT"
          echo "Built JWT length = $(wc -c < token.txt)"

      - name: Send one silent push (sandbox)
        run: |
          set -euo pipefail
          HOST="https://api.sandbox.push.apple.com"   # ← sandbox 固定
          TOPIC="net.momo.CoreBluetoothLE"
          TOKEN="1163bccf16a01f9efae34df9ce464c56e7915cc4172b398640ee1fea581542be2"

          TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          RESP=$(
            curl --http2 -sS -i -w "\n%{http_code}" \
              -H "authorization: bearer ${{ steps.jwt.outputs.token }}" \
              -H "apns-topic: ${TOPIC}" \
              -H "apns-push-type: background" \
              -H "apns-priority: 5" \
              -d "{\"aps\":{\"content-available\":1},\"ts\":\"${TS}\"}" \
              "${HOST}/3/device/${TOKEN}"
          )

          CODE=$(echo "$RESP" | tail -n1)
          echo "=== HTTP Status Code ==="
          echo "$CODE"
          echo "=== Response (headers+body) ==="
          echo "$RESP" | sed '$d'

          if [ "$CODE" = "200" ] || [ "$CODE" = "204" ]; then
            echo "✅ Silent push sent successfully!"
          else
            echo "❌ Failed (HTTP $CODE)"
            exit 1
          fi
