name: one-off-inline-apns
on:
  workflow_dispatch: {}   # Actions に Run workflow ボタンを出す

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # JWT作成だけなので 3.12 が安定

      - name: Install deps
        run: |
          python -V
          pip install "PyJWT>=2.8" "cryptography>=42"

      # 1) Python で JWT を作成（shell: python を使う＝YAMLと衝突しない）
      - name: Build JWT
        id: jwt
        shell: python
        run: |
          import time, os, jwt
          from cryptography.hazmat.primitives import serialization

          # ==== あなたの値（ハードコードでまず通す） ====
          TEAM_ID = "8KVP2QK7BX"
          KEY_ID  = "5W5TK89GQC"
          P8_PEM = """-----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfUyrzATs1Sjn4u9w
          YeJH3LGx67sZPBoVJxHW3C7+dDWgCgYIKoZIzj0DAQehRANCAAQ+sq5rw5HiL6Jo
          LsGWWVfDqTmnYR9LqkKWG3ea+7flLPbRo6UKyuRyQXZ/wrRmVMR+Q5IkrPt4ogIt
          Mig6kHa4
          -----END PRIVATE KEY-----"""
          # =============================================

          private_key = serialization.load_pem_private_key(P8_PEM.encode("utf-8"), password=None)
          token = jwt.encode({"iss": TEAM_ID, "iat": int(time.time())},
                             private_key, algorithm="ES256", headers={"kid": KEY_ID})

          # 出力を次ステップに渡す
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"token={token}\n")

      # 2) curl(HTTP/2) で APNs に送信
      - name: Send APNs via HTTP/2 (curl)
        shell: bash
        env:
          JWT: ${{ steps.jwt.outputs.token }}
        run: |
          set -euo pipefail
          echo "curl version:"
          curl -V

          TOKEN="175946c5bde824e9d31e04660c640915323fa5cfcc15b316c5f1c8c026d1af80"   # 開発トークン
          TOPIC="net.momo.CoreBluetoothLE"                                          # Bundle ID
          HOST="https://api.sandbox.push.apple.com"                                  # TestFlight時は production に変更

          set -x
          curl --http2 -sS -D /tmp/headers.txt \
            -H "authorization: bearer ${JWT}" \
            -H "apns-topic: ${TOPIC}" \
            -H "apns-push-type: background" \
            -H "apns-priority: 5" \
            -d '{"aps":{"content-available":1}}' \
            "${HOST}/3/device/${TOKEN}" \
            -o /tmp/body.json
          set +x

          echo "=== Response Headers ==="
          cat /tmp/headers.txt || true
          echo "=== Response Body ==="
          cat /tmp/body.json || true
