name: one-off-inline-apns
on:
  workflow_dispatch: {}   # ← Actions に「Run workflow」ボタンが出ます（push/prは外しています）

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # JWTだけ作るので 3.12 で安定

      - name: Install minimal deps
        run: |
          python -V
          pip install "PyJWT>=2.8" "cryptography>=42"

      - name: Send APNs via curl (HTTP/2)
        shell: bash
        run: |
          set -euo pipefail
          echo "curl version (HTTP2 必須) ↓"; curl -V

          # === 1) Python で JWT を生成（あなたの値をハードコード） ===
          JWT=$(
python - <<'PY'
import time, jwt
from cryptography.hazmat.primitives import serialization

TEAM_ID = "8KVP2QK7BX"
KEY_ID  = "5W5TK89GQC"
P8_PEM = """-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfUyrzATs1Sjn4u9w
YeJH3LGx67sZPBoVJxHW3C7+dDWgCgYIKoZIzj0DAQehRANCAAQ+sq5rw5HiL6Jo
LsGWWVfDqTmnYR9LqkKWG3ea+7flLPbRo6UKyuRyQXZ/wrRmVMR+Q5IkrPt4ogIt
Mig6kHa4
-----END PRIVATE KEY-----"""
priv = serialization.load_pem_private_key(P8_PEM.encode("utf-8"), password=None)
token = jwt.encode({"iss": TEAM_ID, "iat": int(time.time())}, priv,
                   algorithm="ES256", headers={"kid": KEY_ID})
print(token)
PY
          )
          echo "Built JWT length = ${#JWT}"

          # === 2) 送信先（開発: sandbox） ===
          TOKEN="175946c5bde824e9d31e04660c640915323fa5cfcc15b316c5f1c8c026d1af80"  # 開発トークン
          TOPIC="net.momo.CoreBluetoothLE"                                         # Bundle ID
          HOST="https://api.sandbox.push.apple.com"                                # TestFlightは production に変更

          # === 3) APNs に HTTP/2 で送信（サイレントPush） ===
          set -x
          curl --http2 -sS -D /tmp/headers.txt \
            -H "authorization: bearer ${JWT}" \
            -H "apns-topic: ${TOPIC}" \
            -H "apns-push-type: background" \
            -H "apns-priority: 5" \
            -d '{"aps":{"content-available":1}}' \
            "${HOST}/3/device/${TOKEN}" \
            -o /tmp/body.json
          set +x

          echo "=== Response Headers ==="; cat /tmp/headers.txt || true
          echo "=== Response Body ===";   cat /tmp/body.json  || true
